/*
VICERRECTORADO DE INVESTIGACION
*/

insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('4', 'VICERRECTORADO DE INVESTIGACION', 'A', 'VICERRECTORADO DE INVESTIGACION');

insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('4.1', 'VICERRECTOR DE INVESTIGACIÓN', 'A', 'VICERRECTOR DE INVESTIGACIÓN');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('4.2', 'VRI  SECRETARIA', 'A', 'VRI  SECRETARIA');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('4.3', 'VRI  DIRECCION', 'A', 'VRI  DIRECCION');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('4.4', 'DIRECCIÓN DE EVALUACIÓN, TRANSFERENCIA, TECNOLÓGICA Y PATENTES', 'A', 'DIR EVAL, TRANSF, TEC Y PAT');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('4.5', 'EDITORIAL UNIVERSITARIA', 'A', 'EDITORIAL UNIVERSITARIA');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('4.6', 'OFICINA DE CAPACITACIÓN', 'A', 'OFICINA DE CAPACITACIÓN');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('4.4', 'DIRECCIÓN DE EVALUACIÓN, TRANSFERENCIA, TECNOLÓGICA Y PATENTES', 'A', 'DIR EVAL, TRANSF, TEC Y PAT');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('4.8', 'REPOSITORIO INSTITUCIONAL', 'A', 'REPOSITORIO INSTITUCIONAL');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('4.9', 'ICICYT SECRETARIA', 'A', 'ICICYT SECRETARIA');


insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('vri', '123', '11111137', 'A', null, null, null, null, null, 4.1, null, 1, null);
insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('vri.mesadepartes', '123', '11111137', 'A', null, null, null, null, null, 4.2, null, 1, null);
insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('vri.patentes', '123', '11111137', 'A', null, null, null, null, null, 4.4, null, 1, null);
insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('vri.editorial', '123', '11111137', 'A', null, null, null, null, null, 4.5, null, 1, null);
insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('vri.capacitacion', '123', '11111137', 'A', null, null, null, null, null, 4.6, null, 1, null);
insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('vri.agroindustria', '123', '11111137', 'A', null, null, null, null, null, 4.7, null, 1, null);
insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('vri.repositorio', '123', '11111137', 'A', null, null, null, null, null, 4.8, null, 1, null);
insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('vri.icicyt', '123', '11111137', 'A', null, null, null, null, null, 4.9, null, 1, null); 



/*
POSGRADO
*/

insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('83', 'POSGRADO', 'A', 'POSGRADO');

insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('83.1', 'DIRECTOR DE LA ESCUELA DE POSGRADO', 'A', 'DIRECTOR DE LA ESCUELA DE POSGRADO');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('83.2', 'SECRETARIA', 'A', 'SECRETARIA');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('83.3', 'SECRETARIA ACADEMICA', 'A', 'SECRETARIA ACADEMICA');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('83.4', 'CALIDAD ACADEMICA Y ACREDITACION', 'A', 'CALIDAD ACADEMICA Y ACREDITACION');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('83.5', 'PLANEAMIENTO Y GESTION ECONOMICA', 'A', 'PLANEAMIENTO Y GESTION ECONOMICA');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('83.6', 'ADMISION, PUBLICACIONES Y MARKETING', 'A', 'ADMISION, PUBLICACIONES Y MARKETING');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('83.7', 'COMISION DE CERTIFICADOS Y GRADOS', 'A', 'COMISION DE CERTIFICADOS Y GRADOS');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('83.8', 'COMISION DE CURRICULUM, CONVALIDACION Y REVALIDACION', 'A', 'COM CURR, CONVALID Y REVAL');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('83.9', 'COMISION DE CONVENIOS E INTERCAMBIOS ACADEMICOS', 'A', 'COM CONV E INTERCAM ACAD');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('83.10', 'OTIC DE LA ESCUELA DE POSGRADO', 'A', 'OTIC DE LA ESCUELA DE POSGRADO');


insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('posgrado', '123', '11111137', 'A', null, null, null, null, null, 83.1, null, 1, null);
insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('posgrado.mesadepartes', '123', '11111138', 'A', null, null, null, null, null, 83.2, null, 1, null);
insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('posgrado.academica', '123', '11111139', 'A', null, null, null, null, null, 83.3, null, 1, null);
insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('pogrado.calidad', '123', '11111140', 'A', null, null, null, null, null, 83.4, null, 1, null);
insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('posgrado.planeamiento', '123', '11111141', 'A', null, null, null, null, null, 83.5, null, 1, null);
insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('posgrado.admision', '123', '11111142', 'A', null, null, null, null, null, 83.6, null, 1, null);
insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('posgrado.certificados', '123', '11111143', 'A', null, null, null, null, null, 83.7, null, 1, null);
insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('posgrado.convalidacion', '123', '11111144', 'A', null, null, null, null, null, 83.8, null, 1, null); 
insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('posgrado.convenios', '123', '11111145', 'A', null, null, null, null, null, 83.9, null, 1, null);
insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('posgrado.otic', '123', '11111146', 'A', null, null, null, null, null, 83.10, null, 1, null); 






/*
FACULTAD DE CIENCIAS ADMINISTRATIVAS
*/

insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('22', 'FACULTAD DE CIENCIAS ADMINISTRATIVAS', 'A', 'FCA');

insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('22.1', 'DECANO DE LA FACULTAD DE CIENCIAS ADMINISTRATIVAS', 'A', 'DECANO FCA');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('22.2', 'FCA - Secretaria de Decanato', 'A', 'SECRETARIA FCA');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('22.3', 'FCA - Unidad de Posgrado', 'A', 'POSGRADO FCA');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('22.4', 'FCA - Departamento Académico de Administración', 'A', 'DPTO ACAD FCA');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('22.5', 'FCA - Direccion de Escuela Profesional de Administración', 'A', 'ESCUELA PROF FCA');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('22.6', 'FCA - Oficina de Calidad Académica y Acreditación', 'A', 'MARKETING FCA');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('22.7', 'FCA - Grados y Titulos ', 'A', 'GYT FCA');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('22.8', 'FCA - Publicidad y Marketing/Varios', 'A', 'MARKETING FCA');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('22.9', 'FCA - Servicios Generales', 'A', 'SERV GEN FCA');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('22.10', 'FCA - Biblioteca Especializada', 'A', 'BIBLIOTECA FCA');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('22.11', 'FCA - OTIC', 'A', 'OTIC FCA');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('22.12', 'FCA - Mesa de Partes', 'A', 'MESA FCA');
insert into GENE_DEPENDENCIA (V_IDDEP, V_DESDEP, V_ESTADO, V_SIGLADEP)
values ('22.13', 'FCA - Centro de Extensión y Responsabilidad Social', 'A', 'CERS FCA');


insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('fca.decano', '123', '11111147', 'A', null, null, null, null, null, 22.1, null, 1, null);
insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('fca.mesadepartes', '123', '11111148', 'A', null, null, null, null, null, 22.2, null, 1, null);
insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('fca.posgrado', '123', '11111149', 'A', null, null, null, null, null, 22.3, null, 1, null);
insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('fca.da', '123', '11111150', 'A', null, null, null, null, null, 22.4, null, 1, null);
insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('fca.dep', '123', '11111151', 'A', null, null, null, null, null, 22.5, null, 1, null);
insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('fca.calidad', '123', '11111152', 'A', null, null, null, null, null, 22.6, null, 1, null);
insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('fca.gradosytitulos', '123', '11111153', 'A', null, null, null, null, null, 22.7, null, 1, null);
insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('fca.marketing', '123', '11111154', 'A', null, null, null, null, null, 22.8, null, 1, null); 
insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('fca.serviciosgenerales', '123', '11111155', 'A', null, null, null, null, null, 22.9, null, 1, null);
insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('fca.biblioteca', '123', '11111156', 'A', null, null, null, null, null, 22.10, null, 1, null);
insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('fca.otic', '123', '11111157', 'A', null, null, null, null, null, 22.11, null, 1, null);
insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('fca.mesadepartes2', '123', '11111158', 'A', null, null, null, null, null, 22.12, null, 1, null);
insert into SEGU_USUARIO (CODUSUARIO, PASSWORD, CODPERSONAL, ESTADO, FECREG, USUREG, FECHMOD, USUMOD, CODPERFIL, V_IDDEPTRAM, V_IDDEP2TRAM, V_FLGTRAMITE, IPREG)
values ('fca.ceres', '123', '11111159', 'A', null, null, null, null, null, 22.13, null, 1, null);


























